# .github/workflows/sync.yml
name: Sync Fork

on:
  # 推送代码后触发
  push:
  # 定时任务触发，使用 cron 规则，这里默认一小时执行一次
  schedule:
    - cron: '* */3 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          # 使用自己的用户名替换 username
          git config --global user.name 'rayen'
          git config --global user.email 'rayenofjri@gmail.com'

          git pull --unshallow
          git remote add upstream https://github.com/openwrt/openwrt.git
          git fetch upstream

          # 可以自定义要同步的分支
          git checkout -b v22.03.0-rc4 origin/v22.03.0-rc4
          git merge --no-edit upstream/v22.03.0-rc4
